/**
 * Typed loader for the pre-generated sample listings stored in
 * `data/sample-listings.json`. Generated by `scripts/generate-samples.ts`.
 *
 * Surfaced on each pSEO page so Google sees ~400 words of unique content
 * (title + 5 bullets + description) per (platform, category) combination
 * — instead of the same shared template skeleton across 36 pages.
 */

import samples from "@/data/sample-listings.json";

export interface SampleListing {
  title: string;
  bullets: string[];
  description: string;
  backendKeywords: string;
  seoKeywords: string[];
}

const SAMPLES: Record<string, SampleListing> = samples as Record<
  string,
  SampleListing
>;

export function getSampleListing(
  platform: string,
  categorySlug: string
): SampleListing | null {
  return SAMPLES[`${platform}-${categorySlug}`] ?? null;
}
